version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
      - run:
          name: deploy
          command: npm run deploy
