version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run deploy
